/**
 * Created by HIAPAD on 2018/6/13.
 */
var news = [
    {
        id: 0,
        title: "掌里通智慧城市布局手机点餐系统",
        img: "https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png?imageView&thumbnail=750x0&quality=85&type=jpg&interlace=1",
        summary: "随着智能手机的不断普及，2G、3G、4G、5G甚至将来的更高级别的手机互联网络的不断推陈出新，通过手机实现上网将变的越来越流畅，这将带来手机上网比例不断攀升。现在出门可以不带钱、不带银行卡，但是不能不带手机。满大街的“低头族”告诉我们，手机已成为人类生活和工作中的至关重要的工具。并且人类对更方便快捷的工作和生活方式的追求是无止尽的。“民以食为天",
        content: ["<div class=\"content\">",
            "        <div class=\"page js-page on\">",
            "            <p>随着智能手机的不断普及，2G、3G、4G、5G甚至将来的更高级别的手机互联网络的不断推陈出新，通过手机实现上网将变的越来越流畅，这将带来手机上网比例不断攀升。现在出门可以不带钱、不带银行卡，但是不能不带手机。满大街的“低头族”告诉我们，手机已成为人类生活和工作中的至关重要的工具。并且人类对更方便快捷的工作和生活方式的追求是无止尽的。“民以食为天”，传统餐饮业于互联网的融合更是大势所趋，“掌里通智慧餐饮管理系统”紧密贴合市场所需，解民生之所需，未来的市场将不可限量。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>近日，掌里通智慧城市给广州带来了最新的手机点餐解决方案，结合“吃在广州” 的特质，给出了手机智慧点餐的方案，将在未来让广州这个“美食之都”的餐饮业大大提质增效。</p><p>掌里通智慧城市创始人凌腾云表示，从自助化程度高低进行划分，餐饮业的点餐方式已经从 1.0 的收银台点餐、2.0 的机器点餐，逐步进入 3.0 的手机点餐时代。无论是从互动、体验、成本、还是消费频次上，手机点餐已经成为商家门店跟消费者之间的全新沟通方式。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>而在手机点餐目前主要的APP点餐、H5点餐、掌里通点餐三种方式。从开发维护成本、用户获取门槛、流程体验效果、用户留存、消息触达能力进行分析。掌里通的模式都更轻更好，更有潜力成为未来手机点餐的主流模式。</p><p>凌腾云表示，用掌里通点餐解决方案帮助商家在点餐环节上提升餐厅运营效率，讲引导顾客消费，带来客单量的进一步提升。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>凌腾云介绍，作为“美食之都”，在餐饮业发展方面有着天然优势，掌里通智慧城市立足在广州也是看中了广州身上这种优良的餐饮文化基因，接下来，广州将是手机点餐布局的重要战场。同时，通过这种优化，也将大大实现广州餐饮业服务的新升级。掌里通智慧城市已经覆盖了微餐、快餐、饮品、点餐平台排队预约服务等。</p></div><div class=\"page js-page\"><div class=\"photo\">",
            "        <a href=\"https://cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png\">",
            "            <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "            <span></span>",
            "        </a>",
            "    </div><p>凌腾云介绍，“智慧餐饮管理系统”全新面世，预订系统能够让用户随时随地向商家下单，节省了在餐厅排队等待的时间，预定成功后系统随即自动生成邀请函(邀请函包括餐厅名字，就餐时间，联系电话、地址)并发送到顾客的手机，顾客可以将此邀请函发给其他好友，同时页面会自动生成导航带你直接准确到达餐厅。预定成功后，用户还可以用掌里通智能餐饮预定系统在餐厅提前点餐，将菜单发送给同行好友，大大缩短用户的等待时间，餐厅就可以提前准备点单的菜式。当用户到达餐厅时即可享用，用户也可到店使用智能系统扫码点菜点菜、加菜等各种功能。商家还可通过掌里通与自身门店管理、订单管理、收银系统、运营流程等环节打通，进一步提升运营效率，为门店带来更多客源，提升盈利。全程智能化、自助化，大大提高服务效率。</p><p>此外，掌里通智慧城市各项功能展示清晰、商家进驻便利。进驻后可根据简单易操作的后台提示自行搭建，商家的优惠活动、特价商品可以即时、随心上传。更有二维码即时打印机，即刻生成专属于您的店铺收款二维码。</p><p>智慧城市是一个面向所有人类、为全人类服务大工程。“智慧城市”目标是使人类能更加便捷、高效地享受城市公共服务、更低成本、更精准地寻找市场并获取经济效益。在政府公共信息传播、政务办公、生活预定、出行计划、生活娱乐、商业推广等方面，“智慧城市”的作用将体现的淋漓尽致，广州掌里通网络科技有限公司打造的手机平台——“掌里通智慧城市”是一个综合性的利商便民平台，“掌里通智慧城市”平台的最终目标是实现“掌里通天下”，让所有人都能享受到“智慧城市”给生活和工作带来的便利。</p><p>(原标题：掌里通智慧城市布局手机点餐系统)</p>",
            "        <div class=\"otitle_editor\">",
            "            <p class=\"otitle\">",
            "                (原标题：掌里通智慧城市布局手机点餐系统)",
            "            </p>",
            "        </div>",
            "    </div>",
            "    </div>"].join(""),
        add_time: "2018-06-12",
        category: 0,
        links: "https://3g.163.com/news/article/D4DHJQS400018AOP.html#adaptation=pc"
    },
    {
        id: 7,
        title: "掌里通智慧城市布局手机点餐系统",
        img: "https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png?imageView&thumbnail=750x0&quality=85&type=jpg&interlace=1",
        summary: "随着智能手机的不断普及，2G、3G、4G、5G甚至将来的更高级别的手机互联网络的不断推陈出新，通过手机实现上网将变的越来越流畅，这将带来手机上网比例不断攀升。现在出门可以不带钱、不带银行卡，但是不能不带手机。满大街的“低头族”告诉我们，手机已成为人类生活和工作中的至关重要的工具。并且人类对更方便快捷的工作和生活方式的追求是无止尽的。“民以食为天",
        content: ["<div class=\"content\">",
            "        <div class=\"page js-page on\">",
            "            <p>随着智能手机的不断普及，2G、3G、4G、5G甚至将来的更高级别的手机互联网络的不断推陈出新，通过手机实现上网将变的越来越流畅，这将带来手机上网比例不断攀升。现在出门可以不带钱、不带银行卡，但是不能不带手机。满大街的“低头族”告诉我们，手机已成为人类生活和工作中的至关重要的工具。并且人类对更方便快捷的工作和生活方式的追求是无止尽的。“民以食为天”，传统餐饮业于互联网的融合更是大势所趋，“掌里通智慧餐饮管理系统”紧密贴合市场所需，解民生之所需，未来的市场将不可限量。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>近日，掌里通智慧城市给广州带来了最新的手机点餐解决方案，结合“吃在广州” 的特质，给出了手机智慧点餐的方案，将在未来让广州这个“美食之都”的餐饮业大大提质增效。</p><p>掌里通智慧城市创始人凌腾云表示，从自助化程度高低进行划分，餐饮业的点餐方式已经从 1.0 的收银台点餐、2.0 的机器点餐，逐步进入 3.0 的手机点餐时代。无论是从互动、体验、成本、还是消费频次上，手机点餐已经成为商家门店跟消费者之间的全新沟通方式。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>而在手机点餐目前主要的APP点餐、H5点餐、掌里通点餐三种方式。从开发维护成本、用户获取门槛、流程体验效果、用户留存、消息触达能力进行分析。掌里通的模式都更轻更好，更有潜力成为未来手机点餐的主流模式。</p><p>凌腾云表示，用掌里通点餐解决方案帮助商家在点餐环节上提升餐厅运营效率，讲引导顾客消费，带来客单量的进一步提升。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>凌腾云介绍，作为“美食之都”，在餐饮业发展方面有着天然优势，掌里通智慧城市立足在广州也是看中了广州身上这种优良的餐饮文化基因，接下来，广州将是手机点餐布局的重要战场。同时，通过这种优化，也将大大实现广州餐饮业服务的新升级。掌里通智慧城市已经覆盖了微餐、快餐、饮品、点餐平台排队预约服务等。</p></div><div class=\"page js-page\"><div class=\"photo\">",
            "        <a href=\"https://cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png\">",
            "            <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "            <span></span>",
            "        </a>",
            "    </div><p>凌腾云介绍，“智慧餐饮管理系统”全新面世，预订系统能够让用户随时随地向商家下单，节省了在餐厅排队等待的时间，预定成功后系统随即自动生成邀请函(邀请函包括餐厅名字，就餐时间，联系电话、地址)并发送到顾客的手机，顾客可以将此邀请函发给其他好友，同时页面会自动生成导航带你直接准确到达餐厅。预定成功后，用户还可以用掌里通智能餐饮预定系统在餐厅提前点餐，将菜单发送给同行好友，大大缩短用户的等待时间，餐厅就可以提前准备点单的菜式。当用户到达餐厅时即可享用，用户也可到店使用智能系统扫码点菜点菜、加菜等各种功能。商家还可通过掌里通与自身门店管理、订单管理、收银系统、运营流程等环节打通，进一步提升运营效率，为门店带来更多客源，提升盈利。全程智能化、自助化，大大提高服务效率。</p><p>此外，掌里通智慧城市各项功能展示清晰、商家进驻便利。进驻后可根据简单易操作的后台提示自行搭建，商家的优惠活动、特价商品可以即时、随心上传。更有二维码即时打印机，即刻生成专属于您的店铺收款二维码。</p><p>智慧城市是一个面向所有人类、为全人类服务大工程。“智慧城市”目标是使人类能更加便捷、高效地享受城市公共服务、更低成本、更精准地寻找市场并获取经济效益。在政府公共信息传播、政务办公、生活预定、出行计划、生活娱乐、商业推广等方面，“智慧城市”的作用将体现的淋漓尽致，广州掌里通网络科技有限公司打造的手机平台——“掌里通智慧城市”是一个综合性的利商便民平台，“掌里通智慧城市”平台的最终目标是实现“掌里通天下”，让所有人都能享受到“智慧城市”给生活和工作带来的便利。</p><p>(原标题：掌里通智慧城市布局手机点餐系统)</p>",
            "        <div class=\"otitle_editor\">",
            "            <p class=\"otitle\">",
            "                (原标题：掌里通智慧城市布局手机点餐系统)",
            "            </p>",
            "        </div>",
            "    </div>",
            "    </div>"].join(""),
        add_time: "2018-06-12",
        category: 1,
        links: "https://3g.163.com/news/article/D4DHJQS400018AOP.html#adaptation=pc"
    },
    {
        id: 4,
        title: "好消息：地铁九号线清塘站6月底即将开通！",
        img: "https://www.gzhd.net/UploadFile/image/20180530/20180530162114_95460.jpg",
        summary: "智慧城市就是运用信息和通信技术手段感测、分析、整合城市运行核心系统的各项关键信息，从而对包括民生、环保、公共安全、城市服务、工商业活动在内的各种需求做出智能响应。其实质是利用先进的信息技术，实现城市智慧式管理和运行，进而为城市中的人创造更美好的生活，促进城市的和谐、可持续成长",
        content: ['<div class="content">',
            '&nbsp;',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">在九号线试运营近半年之后，</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">加建的清塘站日前传来了即将开通的好消息！</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">今天上午，广州地铁发布最新消息，</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">清塘站已基本完成建设任务，</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">正式移交运营部门。</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体;">&nbsp;</p>',
            '<p class="bizsvr_14" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162231_25630.gif" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体;">&nbsp;</p>',
            '<section data-id="92139" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;">',
            '<p class="bizsvr_17" style="margin: 0px; padding: 0px;">这也意味着因结合花都空港核心区相关产业发展需要而后增加的清塘站，经过花都区和地铁参建各方的共同努力，正式进入运营前准备工作，将于6月底开门迎客。</p>',
            '<p class="bizsvr_17" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162114_95460.jpg" alt="" style="border: 0px;"></p>',
            '</section></section><section data-id="92407" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_18" data-width="100%"><section class="bizsvr_19"><section class="bizsvr_20" data-width="100%"><section class="bizsvr_21"><strong>克服困难半年后开通</strong></section></section><section class="bizsvr_28" data-width="100%"><section class="bizsvr_29" data-width="100%"><br>',
            '</section></section></section></section></section></section><section data-id="91857" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-role="paragraph" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_30" data-width="100%"><section class="bizsvr_31"><section class="bizsvr_32" data-width="98%"><section class="bizsvr_33">',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">清塘站，是九号线开建后新增的一个地铁站。据广州地铁集团党委宣传部主管陈子昕介绍，2015年，为加快花都区空港核心区的发展，市政府决定在九号线高增站至清㘵站之间增设一个站。据广州地铁介绍，在一个基本成型的盾构隧道加建一个车站，在中国地铁历史上并不多见。决定加建清塘站的时候，九号线土建工程已完成70%以上，清塘站范围内的盾构隧道已建设完成，因此，车站的建设需截断并拆除已建成的盾构隧道管片，并克服多个施工难题。</span></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><span class="bizsvr_1">&nbsp;<br>',
            '</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">据广州地铁集团建设总部九号线土建负责人肖瑞传介绍，清塘站建设过程中先后攻克了岩溶地区溶洞处理、地下连续墙、端头咬合桩、车站抗拔桩、既有隧道拆除、基坑开挖、主体结构与端头冷冻交叉施工等一个个难题，顺利完成车站主体建设。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<p style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<div style="text-align: center;"><strong class="bizsvr_50"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162517_92380.jpg" alt="" width="890" height="1179" title="" align="" style="border: 0px;"></strong></div>',
            '<strong class="bizsvr_50">一是管线迁改量大。</strong>',
            '<p style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="85598" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_45"><section class="bizsvr_48"><section style="color: inherit; padding-bottom: 10px; box-sizing: border-box;">',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">该站涉及南北两侧管线迁改，管线种类繁多，具体有：雨水管、供水管、通信、电信、燃气管、污水管、电力管等，且所处的迎宾大道是花都区的主干道，北有嘉华酒店、南有绿地楼盘，迁改路由可选择的局限性大，迁改工作十分困难。为此，地铁公司积极协调各方，在花都区政府的帮助下，疏解道路施工作业与管线迁改同步进行，于</span><span class="bizsvr_1">2016</span><span class="bizsvr_1">年</span><span class="bizsvr_1">8</span><span class="bizsvr_1">月底完成了车站主体结构范围内的全部管线迁改。</span></p>',
            '</section></section></section></section><section data-id="85598" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_45"><section class="bizsvr_46"><section class="bizsvr_47"><strong><span class="bizsvr_1">二是见洞率超过</span><span class="bizsvr_1">50%</span><span class="bizsvr_1">。</span></strong></section></section><section class="bizsvr_48"><section style="color: inherit; padding-bottom: 10px; box-sizing: border-box;">',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">九号线位于岩溶发育区，而清塘站范围内溶洞发育，地下水丰富，岩面高低起伏大，见洞率</span><span class="bizsvr_1">50.7%</span><span class="bizsvr_1">，其中两层以上岩溶占揭露岩溶钻孔的</span><span class="bizsvr_1">13.6%</span><span class="bizsvr_1">。为此，施工前预先对车站范围内溶洞、土洞进行了探边、注浆填充处理，车站最终完成全部顶板浇筑。</span></p>',
            '</section></section></section></section><section data-id="85598" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_45"><section class="bizsvr_46"><section class="bizsvr_47"><strong><span class="bizsvr_1">三是安全拆除既有隧道</span><span class="bizsvr_1">。</span></strong></section></section><section class="bizsvr_48"><section style="color: inherit; padding-bottom: 10px; box-sizing: border-box;">',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">由于清塘站开始建设时，该区间隧道己建成，这就需要钻穿新增车站范围内的既有隧道管片。为保证已经成型隧道完整和安全，地铁建设者采用了创新的咬合桩工法。先在车站端头处隧道内浇筑挡墙，然后填充泡沫混凝土，再采用全回转套管钻机施工咬合桩钻破端头盾构管片，基坑开挖至底部后，在隧道洞口四周水平冷冻加固确保原有隧道安全。</span></p>',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<div style="text-align: center;"><span style="color: inherit;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162611_69590.jpg" alt="" style="border: 0px;"></span></div>',
            '<p style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '</section></section></section></section></section></section></section></section></section></section><section data-id="92238" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-id="92407" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_18" data-width="100%"><section class="bizsvr_19"><section class="bizsvr_24"><section class="bizsvr_25" data-width="100%">',
            '<p class="bizsvr_26" data-width="100%" style="margin: 0px; padding: 0px;"><span class="bizsvr_27"><strong>车站服务看齐九号线</strong></span></p>',
            '</section></section><section class="bizsvr_28" data-width="100%"><section class="bizsvr_29" data-width="100%"><img src="https://mmbiz.qpic.cn/mmbiz_png/6t9RGK4uzsqibvvy7LG3w5shAicJO1ahZE81jxgyUicWShDXXIkcwaicXVgOgRx90MyNQ0mgekzacUFytiaatr21HwA/640?wx_fmt=png" data-w="135" data-type="png" data-src="https://mmbiz.qpic.cn/mmbiz_png/6t9RGK4uzsqibvvy7LG3w5shAicJO1ahZE81jxgyUicWShDXXIkcwaicXVgOgRx90MyNQ0mgekzacUFytiaatr21HwA/640?wx_fmt=png" data-ratio="0.18518518518518517" _width="80px" style="border: 0px; display: block; width: 80px !im<em></em>portant; height: 14.81px !im<em></em>portant;" alt=""></section></section></section></section></section></section></section><section data-id="91857" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-role="paragraph" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_30" data-width="100%"><section class="bizsvr_31"><section class="bizsvr_32" data-width="98%"><section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">据广州地铁集团运营总部九号线车站服务负责人张瑜亮介绍，清塘站位于迎宾大道与清塘路的交叉路口，设有<span class="bizsvr_101">4出入口</span>，其中：<span class="bizsvr_101">A口有合和新城小区，B口有空港物流园，C口附近是广塘村，D口有花都皇冠假日酒店、嘉都汇小区。</span>开通后，将给周边市民出行带来更多的便利。</span></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162704_14760.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162704_27070.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162705_12120.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">而在服务方面，清塘站四个出入口均设有双向扶梯和楼梯，B口还设置有专用电梯和坡道，为乘客出行提供了便利。</span></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162727_53680.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_114" style="margin: 0px; padding: 0px;"><span class="bizsvr_115">同时，清塘站将继续沿袭去年九号线开通的“优良传统”，服务全面升级。</span></p>',
            '<p class="bizsvr_116" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>购票方式更智能。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">包括广州地铁官方APP乘车二维码、ApplePay、金融IC卡、云卡及地铁乘车码等多种非现金支付方式，在开通后即能同步使用。同时，车站设有多台自动售票机可实现扫描支付和购票，乘客购票无需找零钱。</span></p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162822_04400.jpg" alt="" style="border: 0px;"></p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>车站设有洗手间。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为了满足乘客乘坐地铁期间的如厕需求，车站在站台设有洗手间。</span></p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162902_25240.jpg" alt="" width="800" height="604" title="" align="" style="border: 0px;"></p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162902_46230.jpg" alt="" style="border: 0px;"></p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>增设自动补票机。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为方便乘客处理票务事务，乘客可通过自助补票机自行补票，大大节约了人工补票的等候时间。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>设宽通道闸机。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为了提高携带大件行李、推婴儿车等乘客的进站效率，车站在两端分别设置了1台宽通道闸机。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>增加母婴室。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为了给哺乳乘客提供私密的舒适的空间，车站在站厅设有独立的母婴室，配置座椅、婴儿护理台等。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>引入多元共享服务。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">在原有人工租借便民雨伞服务的基础上，引入共享雨伞，实现了借还全智能化，更好地满足雨天乘客出行的借伞需求。</span></p>',
            '</section></section></section></section></section></section>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;">&nbsp;</p>',
            '<section data-id="92407" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_18" data-width="100%"><section class="bizsvr_19"><section class="bizsvr_20" data-width="100%"><section class="bizsvr_21"><br>',
            '</section></section><section class="bizsvr_24"><section class="bizsvr_25" data-width="100%">',
            '<p class="bizsvr_26" data-width="100%" style="margin: 0px; padding: 0px;"><span class="bizsvr_27"><strong>开通半年客流逐步增加</strong></span></p>',
            '</section></section><section class="bizsvr_28" data-width="100%"><section class="bizsvr_29" data-width="100%"><br>',
            '</section></section></section></section></section></section><section data-id="92238" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-id="91857" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section data-role="paragraph" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_30" data-width="100%"><section class="bizsvr_31"><section class="bizsvr_32" data-width="98%"><section class="bizsvr_33">',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_188">九号线自去年12月<span class="bizsvr_189">28</span>日开通以来已有半年，运营情况怎么样？清塘站开通后，九号线的客流又将有哪些变化？30日上午，广州地铁在宣布清塘站开通消息的同时，也公布了九号线半年来的有关运营数据。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_188">据广州地铁介绍，截至5月<span class="bizsvr_189">20</span>日，九号线行车间隔约6分半钟<span class="bizsvr_189">，</span>最大满载率<span class="bizsvr_189">46%</span>，列车准点率达到99.99%，日开行列车293列次，累计开行列车4.2万列次。日均客流量近<span class="bizsvr_189">10</span>万人次，三号线与九号线的日均换乘客流量达<span class="bizsvr_189">3.6</span>万人次，最高日客流量在今年1月<span class="bizsvr_189">1</span>日，超过了19万人次。全线工作日的客流高峰期集中在上午<span class="bizsvr_189">7</span>点至<span class="bizsvr_189">8</span>点，而全线客流量前三个车站分别是：高增站3.7万人次、花都广场站<span class="bizsvr_189">1.4</span>万人次、花城路站<span class="bizsvr_189">1.2</span>万人次。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_188">广州地铁表示，随着市民对九号线的日渐熟悉，九号线的客流稳步上升，日均客流量从1月份的<span class="bizsvr_189">9</span>万余人次，逐步增加至5月份的<span class="bizsvr_189">10</span>万余人次。考虑新线客流培育的影响预计到下半年日均客运量有望突破<span class="bizsvr_189">11</span>万。</span></p>',
            '</section></section></section></section></section></section></section></div>'].join(""),
        add_time: "2018-5-31",
        category: 0,
        links: "https://www.zhanglitong.com/mobile/index.php?moduleid=21&itemid=1659"
    },
    {
        id: 1,
        title: "掌里通智慧城市，一个让生活智能化的平台",
        img: "./images/blog/20161209025801554.png",
        summary: "智慧城市就是运用信息和通信技术手段感测、分析、整合城市运行核心系统的各项关键信息，从而对包括民生、环保、公共安全、城市服务、工商业活动在内的各种需求做出智能响应。其实质是利用先进的信息技术",
        content: ["<div id=\"img-content\">",
            "                ",
            "                <h2 class=\"rich_media_title\" id=\"activity-name\">",
            "                    掌里通智慧城市，一个让生活智能化的平台",
            "                                                                                </h2>",
            "                <div id=\"meta_content\" class=\"rich_media_meta_list\">",
            "                                                                                <span class=\"rich_media_meta rich_media_meta_nickname\" id=\"profileBt\">",
            "                      <a href=\"javascript:void(0);\" id=\"js_name\">",
            "                        掌里通智慧城市                      </a>",
            "                      <div id=\"js_profile_qrcode\" class=\"profile_container\" style=\"display:none;\">",
            "                          <div class=\"profile_inner\">",
            "                              <strong class=\"profile_nickname\">掌里通智慧城市</strong>",
            "                              <img class=\"profile_avatar\" id=\"js_profile_qrcode_img\" src=\"\" alt=\"\">",
            "                              <p class=\"profile_meta\">",
            "                              <label class=\"profile_meta_label\">微信号</label>",
            "                              <span class=\"profile_meta_value\">zltgzh</span>",
            "                              </p>",
            "                              <p class=\"profile_meta\">",
            "                              <label class=\"profile_meta_label\">功能介绍</label>",
            "                              <span class=\"profile_meta_value\">致力于为您提供一个智能化的现代掌上城市。</span>",
            "                              </p>",
            "                              ",
            "                          </div>",
            "                          <span class=\"profile_arrow_wrp\" id=\"js_profile_arrow_wrp\">",
            "                              <i class=\"profile_arrow arrow_out\"></i>",
            "                              <i class=\"profile_arrow arrow_in\"></i>",
            "                          </span>",
            "                      </div>",
            "                    </span>",
            "                    <em id=\"publish_time\" class=\"rich_media_meta rich_media_meta_text\">2017-11-30</em>",
            "                </div>",
            "                ",
            "                ",
            "                ",
            "                ",
            "                                                ",
            "                                                                ",
            "                ",
            "                <div class=\"rich_media_content \" lang=\"=&quot;en&quot;\" id=\"js_content\">",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    <p><span style=\"background-color: rgb(255, 255, 255);\"></span><span style=\"background-color: rgb(255, 255, 255);\"></span></p><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"margin-top: 10px;margin-bottom: 10px;text-align: center;box-sizing: border-box;\"><section class=\"\" style=\"max-width: 100%;vertical-align: middle;display: inline-block;box-sizing: border-box;overflow: hidden !important;\"><img data-ratio=\"1\" data-w=\"640\" data-src=\"http://mmbiz.qpic.cn/mmbiz_jpg/Ay2oOP9oMSyUftXY8XXDll353db13VLaueMlxu4zQfOKZLicd5TeXgyibnZdIt8LRCotpj6zlB0IryvLWhLbibib9g/0/jpeg\" style=\"vertical-align: middle; box-sizing: border-box; width: auto !important; height: auto !important; visibility: visible !important;\" class=\"\" src=\"http://mmbiz.qpic.cn/mmbiz_jpg/Ay2oOP9oMSyUftXY8XXDll353db13VLaueMlxu4zQfOKZLicd5TeXgyibnZdIt8LRCotpj6zlB0IryvLWhLbibib9g/0/jpeg?tp=webp&amp;wxfrom=5&amp;wx_lazy=1\" data-fail=\"0\"></section></section></section><p><br></p><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"padding-right: 10px;padding-left: 10px;color: rgb(24, 55, 246);line-height: 2;letter-spacing: 2px;box-sizing: border-box;\"><p style=\"text-indent: 2em;box-sizing: border-box;\">智慧城市就是运用信息和通信技术手段感测、分析、整合城市运行核心系统的各项关键信息，从而对包括民生、环保、公共安全、城市服务、工商业活动在内的各种需求做出智能响应。其实质是利用先进的信息技术</p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"margin-top: 10px;margin-bottom: 10px;box-sizing: border-box;\"><section class=\"\" style=\"padding: 10px;display: inline-block;width: 516px;border-width: 1px;border-style: solid;border-color: rgb(226, 226, 226);box-shadow: rgb(226, 226, 226) 0px 16px 1px -13px;box-sizing: border-box;\"><section class=\"\" powered-by=\"xiumi.us\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"padding-right: 10px;padding-left: 10px;line-height: 2;letter-spacing: 2px;box-sizing: border-box;\"><p style=\"text-indent: 2em;box-sizing: border-box;\">智慧城市就是运用信息和通信技术手段感测、分析、整合城市运行核心系统的各项关键信息，从而对包括民生、环保、公共安全、城市服务、工商业活动在内的各种需求做出智能响应。其实质是利用先进的信息技术，实现城市智慧式管理和运行，进而为城市中的人创造更美好的生活，促进城市的和谐、可持续成长。</p><p style=\"text-indent: 2em;box-sizing: border-box;\">随着人类社会的不断发展，未来城市将承载越来越多的人口。目前，我国正处于城镇化加速发展的时期，部分地区\"城市病\"问题日益严峻。为解决城市发展难题，实现城市可持续发展，建设智慧城市已成为当今世界城市发展不可逆转的历史潮流。</p></section></section></section></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"margin-top: 10px;margin-bottom: 10px;text-align: center;box-sizing: border-box;\"><section class=\"\" style=\"max-width: 100%;vertical-align: middle;display: inline-block;box-sizing: border-box;overflow: hidden !important;\"><img data-ratio=\"0.75\" data-w=\"640\" data-src=\"http://mmbiz.qpic.cn/mmbiz_jpg/Ay2oOP9oMSyUftXY8XXDll353db13VLawbM0LY08dRpjRT2EuicmmmMRoQFBsniac2BibALSsSEiaujatPTKLZibwZg/0/jpeg\" style=\"vertical-align: middle; box-sizing: border-box; width: auto !important; height: auto !important; visibility: visible !important;\" class=\"\" src=\"http://mmbiz.qpic.cn/mmbiz_jpg/Ay2oOP9oMSyUftXY8XXDll353db13VLawbM0LY08dRpjRT2EuicmmmMRoQFBsniac2BibALSsSEiaujatPTKLZibwZg/0/jpeg?tp=webp&amp;wxfrom=5&amp;wx_lazy=1\" data-fail=\"0\"></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"margin-top: 10px;margin-bottom: 10px;box-sizing: border-box;\"><section class=\"\" style=\"padding: 2px 3px;display: inline-block;width: 516px;vertical-align: top;background-image: url(&quot;http://mmbiz.qpic.cn/mmbiz_gif/WYyEKJXrHW8Omf9bWEeNNPz1oebzBWxjPtnyg2mjXqzlctOPwYkrlK3Bnrp6SwAqnPVm8y7M5CKVKicPZFU3EWw/0/gif&quot;);background-position: 0% 0%;background-repeat: repeat-y;background-size: 100.733%;background-attachment: scroll;line-height: 1.6;box-sizing: border-box;\"><section class=\"\" powered-by=\"xiumi.us\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"margin-top: 1px;margin-bottom: 1px;text-align: center;box-sizing: border-box;\"><section class=\"\" style=\"padding: 10px;display: inline-block;width: 510px;border-width: 1px;border-style: solid;border-color: transparent;background-color: rgb(254, 255, 255);box-sizing: border-box;\"><section class=\"\" powered-by=\"xiumi.us\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"padding-right: 10px;padding-left: 10px;text-align: left;line-height: 2;color: rgb(24, 55, 246);letter-spacing: 2px;box-sizing: border-box;\"><p style=\"box-sizing: border-box;\">如今智慧城市、智能生活已经成为一种各国争相建设、效仿的潮流，简单地举个例子，就像夏天快到了，你再不抓紧甩掉自身的肥肉，那么到时候你非但不能让别人惊艳，还随时可能被别人的好身材给虐死，城市的智慧化变革和减肥一样，是需要痛下决心以及制定目标的。当然啦，减肥不能乱减，减不好是会出人命的，所以减肥需要结合自身情况，制定健康的减肥计划，有需要的话，还要找专业的减肥或健身教练来帮你。而用户需要的智慧城市功能一定需要有技术、有理念的专业平台来帮您实现!</p></section></section></section></section></section></section></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"margin-top: 10px;margin-bottom: 10px;text-align: center;box-sizing: border-box;\"><section class=\"\" style=\"max-width: 100%;vertical-align: middle;display: inline-block;box-sizing: border-box;overflow: hidden !important;\"><img data-ratio=\"0.8625\" data-w=\"640\" data-src=\"http://mmbiz.qpic.cn/mmbiz_jpg/Ay2oOP9oMSyUftXY8XXDll353db13VLaP4OhCiajq0kjqsrSWwUt43pSmLf5UvG6bOFFrbnna5VtkxyvSQMWNZg/0/jpeg\" style=\"vertical-align: middle; box-sizing: border-box; width: 640px !important; height: 552px !important;\" class=\"img_loading\" src=\"data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==\"></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"padding-right: 10px;padding-left: 10px;line-height: 2;color: rgb(24, 55, 246);letter-spacing: 2px;box-sizing: border-box;\"><p style=\"text-indent: 2em;box-sizing: border-box;\">掌里通智慧城市平台的推出，颠覆了传统生活的固守、被动的状态，让传统生活模式发生天翻地覆的改变，由被动变为主动，让人们占领生活的主导权。掌里通指挥平台让商家免费进驻，商户在这里可以出售产品、招聘人员，掌里通移动超市与线下大型卖场、超市对接，大型送货车队、专人配送上门服务，让您足不出户就可以享受到智能、轻奢的生活;;政府也可以通过进驻掌里通智慧城市来提高办事的效率，为人们的日常生活带来很多的便利，优化政府的管理和决策。</p><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p><p style=\"text-indent: 2em;box-sizing: border-box;\">掌里通智慧城市人将会掀开崭新的一页!让我们万众一心，勇往直前，让掌里通平台在广州地区乃至全国迅速落地、开花、结果，用互联网技术建立有序供应可持续的商业环境，成就自己，造福大家!</p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"margin-top: 10px;margin-bottom: 10px;text-align: center;box-sizing: border-box;\"><section class=\"\" style=\"max-width: 100%;vertical-align: middle;display: inline-block;box-sizing: border-box;overflow: hidden !important;\"><img data-ratio=\"0.515625\" data-w=\"640\" data-src=\"http://mmbiz.qpic.cn/mmbiz_jpg/Ay2oOP9oMSyUftXY8XXDll353db13VLaTNPBKFOFCBvDHickJybQiac3Uj2oEuWayCeibeWxWsZmpB7dLTXFVvicvw/0/jpeg\" style=\"vertical-align: middle; box-sizing: border-box; width: 640px !important; height: 330px !important;\" class=\"img_loading\" src=\"data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==\"></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><p style=\"box-sizing: border-box;\"><br style=\"box-sizing: border-box;\"></p></section></section></section><section class=\"\" powered-by=\"xiumi.us\" style=\"white-space: normal;background-color: rgb(255, 255, 255);box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"><section class=\"\" style=\"box-sizing: border-box;\"></section></section></section><p><br></p><p><br></p>",
            "                </div>",
            "                <script nonce=\"442140556\" type=\"text/javascript\">",
            "                    var first_sceen__time = (+new Date());",
            "                    if (\"\" == 1 && document.getElementById(\'js_content\')) {",
            "                        document.getElementById(\'js_content\').addEventListener(\"selectstart\",function(e){ e.preventDefault(); });",
            "                    }",
            "                    ",
            "                    (function(){",
            "                        if (navigator.userAgent.indexOf(\"WindowsWechat\") != -1){",
            "                            var link = document.createElement(\'link\');",
            "                            var head = document.getElementsByTagName(\'head\')[0];",
            "                            link.rel = \'stylesheet\';",
            "                            link.type = \'text/css\';",
            "                            link.href = \"//res.wx.qq.com/mmbizwap/zh_CN/htmledition/style/page/appmsg_new/winwx3de35e.css\";",
            "                            head.appendChild(link);",
            "                        }",
            "                    })();",
            "                </script>",
            "                ",
            "                ",
            "                                ",
            "                <div class=\"ct_mpda_wrp\" id=\"js_sponsor_ad_area\" style=\"display:none;\"></div>",
            "                ",
            "                                <div class=\"reward_area tc reward_area_primary\" id=\"js_preview_reward_author\" style=\"display:none;\">",
            "                    <div class=\"reward-avatar\" style=\"display: none;\" id=\"js_preview_reward_author_avatar\">",
            "                        <img src=\"\" alt=\"\" id=\"js_preview_reward_author_head\">",
            "                    </div>",
            "                    <div class=\"reward-author\" id=\"js_preview_reward_author_name\"></div>",
            "                    <p class=\"reward_tips\" id=\"js_preview_reward_author_wording\" style=\"display:none;\"></p>",
            "                    <p>",
            "                        <a class=\"reward_button\" id=\"js_preview_reward_author_link\" href=\"##\"><span id=\"js_preview_reward_link_text\">赞赏</span></a>",
            "                    </p>",
            "                </div>",
            "                ",
            "                <div class=\"reward_qrcode_area reward_area tc\" id=\"js_preview_reward_qrcode\" style=\"display:none;\">",
            "                    <p class=\"tips_global\">长按二维码向我转账</p>",
            "                    <p id=\"js_preview_reward_ios_wording\" class=\"reward_tips\" style=\"display:none;\"></p>",
            "                    <span class=\"reward_qrcode_img_wrp\"><img class=\"reward_qrcode_img\" src=\"//res.wx.qq.com/mmbizwap/zh_CN/htmledition/images/pic/appmsg/pic_reward_qrcode.2x3534dd.png\"></span>",
            "                    <p class=\"tips_global\">受苹果公司新规定影响，微信 iOS 版的赞赏功能被关闭，可通过二维码转账支持公众号。</p>",
            "                </div>",
            "                            </div>"].join(""),
        add_time: "2017-11-30",
        category: 1,
        links: "https://mp.weixin.qq.com/s/bza6nArMLbZelmS7zkNA_Q"
    },
    {
        id: 3,
        title: "智慧城市就是运用信息",
        img: "./images/blog/1529055371.jpg",
        summary: "智慧城市就是运用信息和通信技术手段感测、分析、整合城市运行核心系统的各项关键信息，从而对包括民生、环保、公共安全、城市服务、工商业活动在内的各种需求做出智能响应。其实质是利用先进的信息技术，实现城市智慧式管理和运行，进而为城市中的人创造更美好的生活，促进城市的和谐、可持续成长",
        content: ["<section class=\"article-text\">",
            "                        &nbsp; &nbsp; &nbsp; &nbsp; 智慧城市就是运用信息和通信技术手段感测、分析、整合城市运行核心系统的各项关键信息，从而对包括民生、环保、公共安全、城市服务、工商业活动在内的各种需求做出智能响应。其实质是利用先进的信息技术，实现城市智慧式管理和运行，进而为城市中的人创造更美好的生活，促进城市的和谐、可持续成长。",
            "<p>　　随着人类社会的不断发展，未来城市将承载越来越多的人口。目前，我国正处于城镇化加速发展的时期，部分地区\"城市病\"问题日益严峻。为解决城市发展难题，实现城市可持续发展，建设智慧城市已成为当今世界城市发展不可逆转的<a href=\"http://www.kejixun.com/kexue/civilization/\" target=\"_blank\" class=\"keylink\">历史</a>潮流。</p>",
            "<center>",
            "	<img alt=\"\" src=\"http://image.kejixun.com/2016/1209/20161209025801554.png\" style=\"height: 216px; width: 400px;\"></center>",
            "<p>　　如今智慧城市、智能生活已经成为一种各国争相建设、效仿的潮流，简单地举个例子，就像夏天快到了，你再不抓紧甩掉自身的肥肉，那么到时候你非但不能让别人惊艳，还随时可能被别人的好身材给虐死，城市的智慧化变革和减肥一样，是需要痛下决心以及制定目标的。当然啦，减肥不能乱减，减不好是会出人命的，所以减肥需要结合自身情况，制定健康的减肥计划，有需要的话，还要找专业的减肥或健身教练来帮你。而用户需要的智慧城市功能一定需要有技术、有理念的专业平台来帮您实现!</p>",
            "<center>",
            "	<img alt=\"\" src=\"http://image.kejixun.com/2016/1209/20161209025807644.png\" style=\"height: 295px; width: 400px;\"></center>",
            "<p>　　掌里通智慧城市平台的推出，颠覆了传统生活的固守、被动的状态，让传统生活模式发生天翻地覆的改变，由被动变为主动，让人们占领生活的主导权。掌里通指挥平台让商家免费进驻，商户在这里可以出售产品、招聘人员，掌里通移动超市与线下大型卖场、超市对接，大型送货车队、专人配送上门服务，让您足不出户就可以享受到智能、轻奢的生活;;政府也可以通过进驻掌里通智慧城市来提高办事的效率，为人们的日常生活带来很多的便利，优化政府的管理和决策。</p>",
            "<p>　　掌里通智慧城市人将会掀开崭新的一页!让我们万众一心，勇往直前，让掌里通平台在广州地区乃至全国迅速落地、开花、结果，用互联网技术建立有序供应可持续的商业环境，成就自己，造福大家!</p>",
            "                    </section>"].join(""),
        add_time: "2016-12-09",
        category: 0
    },
    {
        id: 5,
        title: "好消息：地铁九号线清塘站6月底即将开通！",
        img: "https://www.gzhd.net/UploadFile/image/20180530/20180530162114_95460.jpg",
        summary: "智慧城市就是运用信息和通信技术手段感测、分析、整合城市运行核心系统的各项关键信息，从而对包括民生、环保、公共安全、城市服务、工商业活动在内的各种需求做出智能响应。其实质是利用先进的信息技术，实现城市智慧式管理和运行，进而为城市中的人创造更美好的生活，促进城市的和谐、可持续成长",
        content: ['<div class="content">',
            '&nbsp;',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">在九号线试运营近半年之后，</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">加建的清塘站日前传来了即将开通的好消息！</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">今天上午，广州地铁发布最新消息，</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">清塘站已基本完成建设任务，</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><span class="bizsvr_1">正式移交运营部门。</span></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体;">&nbsp;</p>',
            '<p class="bizsvr_14" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162231_25630.gif" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体;">&nbsp;</p>',
            '<section data-id="92139" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;">',
            '<p class="bizsvr_17" style="margin: 0px; padding: 0px;">这也意味着因结合花都空港核心区相关产业发展需要而后增加的清塘站，经过花都区和地铁参建各方的共同努力，正式进入运营前准备工作，将于6月底开门迎客。</p>',
            '<p class="bizsvr_17" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162114_95460.jpg" alt="" style="border: 0px;"></p>',
            '</section></section><section data-id="92407" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_18" data-width="100%"><section class="bizsvr_19"><section class="bizsvr_20" data-width="100%"><section class="bizsvr_21"><strong>克服困难半年后开通</strong></section></section><section class="bizsvr_28" data-width="100%"><section class="bizsvr_29" data-width="100%"><br>',
            '</section></section></section></section></section></section><section data-id="91857" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-role="paragraph" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_30" data-width="100%"><section class="bizsvr_31"><section class="bizsvr_32" data-width="98%"><section class="bizsvr_33">',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">清塘站，是九号线开建后新增的一个地铁站。据广州地铁集团党委宣传部主管陈子昕介绍，2015年，为加快花都区空港核心区的发展，市政府决定在九号线高增站至清㘵站之间增设一个站。据广州地铁介绍，在一个基本成型的盾构隧道加建一个车站，在中国地铁历史上并不多见。决定加建清塘站的时候，九号线土建工程已完成70%以上，清塘站范围内的盾构隧道已建设完成，因此，车站的建设需截断并拆除已建成的盾构隧道管片，并克服多个施工难题。</span></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><span class="bizsvr_1">&nbsp;<br>',
            '</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">据广州地铁集团建设总部九号线土建负责人肖瑞传介绍，清塘站建设过程中先后攻克了岩溶地区溶洞处理、地下连续墙、端头咬合桩、车站抗拔桩、既有隧道拆除、基坑开挖、主体结构与端头冷冻交叉施工等一个个难题，顺利完成车站主体建设。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<p style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<div style="text-align: center;"><strong class="bizsvr_50"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162517_92380.jpg" alt="" width="890" height="1179" title="" align="" style="border: 0px;"></strong></div>',
            '<strong class="bizsvr_50">一是管线迁改量大。</strong>',
            '<p style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="85598" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_45"><section class="bizsvr_48"><section style="color: inherit; padding-bottom: 10px; box-sizing: border-box;">',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">该站涉及南北两侧管线迁改，管线种类繁多，具体有：雨水管、供水管、通信、电信、燃气管、污水管、电力管等，且所处的迎宾大道是花都区的主干道，北有嘉华酒店、南有绿地楼盘，迁改路由可选择的局限性大，迁改工作十分困难。为此，地铁公司积极协调各方，在花都区政府的帮助下，疏解道路施工作业与管线迁改同步进行，于</span><span class="bizsvr_1">2016</span><span class="bizsvr_1">年</span><span class="bizsvr_1">8</span><span class="bizsvr_1">月底完成了车站主体结构范围内的全部管线迁改。</span></p>',
            '</section></section></section></section><section data-id="85598" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_45"><section class="bizsvr_46"><section class="bizsvr_47"><strong><span class="bizsvr_1">二是见洞率超过</span><span class="bizsvr_1">50%</span><span class="bizsvr_1">。</span></strong></section></section><section class="bizsvr_48"><section style="color: inherit; padding-bottom: 10px; box-sizing: border-box;">',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">九号线位于岩溶发育区，而清塘站范围内溶洞发育，地下水丰富，岩面高低起伏大，见洞率</span><span class="bizsvr_1">50.7%</span><span class="bizsvr_1">，其中两层以上岩溶占揭露岩溶钻孔的</span><span class="bizsvr_1">13.6%</span><span class="bizsvr_1">。为此，施工前预先对车站范围内溶洞、土洞进行了探边、注浆填充处理，车站最终完成全部顶板浇筑。</span></p>',
            '</section></section></section></section><section data-id="85598" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_45"><section class="bizsvr_46"><section class="bizsvr_47"><strong><span class="bizsvr_1">三是安全拆除既有隧道</span><span class="bizsvr_1">。</span></strong></section></section><section class="bizsvr_48"><section style="color: inherit; padding-bottom: 10px; box-sizing: border-box;">',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;"><span class="bizsvr_1">由于清塘站开始建设时，该区间隧道己建成，这就需要钻穿新增车站范围内的既有隧道管片。为保证已经成型隧道完整和安全，地铁建设者采用了创新的咬合桩工法。先在车站端头处隧道内浇筑挡墙，然后填充泡沫混凝土，再采用全回转套管钻机施工咬合桩钻破端头盾构管片，基坑开挖至底部后，在隧道洞口四周水平冷冻加固确保原有隧道安全。</span></p>',
            '<p class="bizsvr_53" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<div style="text-align: center;"><span style="color: inherit;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162611_69590.jpg" alt="" style="border: 0px;"></span></div>',
            '<p style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '</section></section></section></section></section></section></section></section></section></section><section data-id="92238" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-id="92407" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_18" data-width="100%"><section class="bizsvr_19"><section class="bizsvr_24"><section class="bizsvr_25" data-width="100%">',
            '<p class="bizsvr_26" data-width="100%" style="margin: 0px; padding: 0px;"><span class="bizsvr_27"><strong>车站服务看齐九号线</strong></span></p>',
            '</section></section><section class="bizsvr_28" data-width="100%"><section class="bizsvr_29" data-width="100%"><img src="https://mmbiz.qpic.cn/mmbiz_png/6t9RGK4uzsqibvvy7LG3w5shAicJO1ahZE81jxgyUicWShDXXIkcwaicXVgOgRx90MyNQ0mgekzacUFytiaatr21HwA/640?wx_fmt=png" data-w="135" data-type="png" data-src="https://mmbiz.qpic.cn/mmbiz_png/6t9RGK4uzsqibvvy7LG3w5shAicJO1ahZE81jxgyUicWShDXXIkcwaicXVgOgRx90MyNQ0mgekzacUFytiaatr21HwA/640?wx_fmt=png" data-ratio="0.18518518518518517" _width="80px" style="border: 0px; display: block; width: 80px !im<em></em>portant; height: 14.81px !im<em></em>portant;" alt=""></section></section></section></section></section></section></section><section data-id="91857" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-role="paragraph" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_30" data-width="100%"><section class="bizsvr_31"><section class="bizsvr_32" data-width="98%"><section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">据广州地铁集团运营总部九号线车站服务负责人张瑜亮介绍，清塘站位于迎宾大道与清塘路的交叉路口，设有<span class="bizsvr_101">4出入口</span>，其中：<span class="bizsvr_101">A口有合和新城小区，B口有空港物流园，C口附近是广塘村，D口有花都皇冠假日酒店、嘉都汇小区。</span>开通后，将给周边市民出行带来更多的便利。</span></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162704_14760.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162704_27070.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162705_12120.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">而在服务方面，清塘站四个出入口均设有双向扶梯和楼梯，B口还设置有专用电梯和坡道，为乘客出行提供了便利。</span></p>',
            '<p class="bizsvr_36" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162727_53680.jpg" alt="" style="border: 0px;"></p>',
            '<p class="bizsvr_114" style="margin: 0px; padding: 0px;"><span class="bizsvr_115">同时，清塘站将继续沿袭去年九号线开通的“优良传统”，服务全面升级。</span></p>',
            '<p class="bizsvr_116" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>购票方式更智能。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">包括广州地铁官方APP乘车二维码、ApplePay、金融IC卡、云卡及地铁乘车码等多种非现金支付方式，在开通后即能同步使用。同时，车站设有多台自动售票机可实现扫描支付和购票，乘客购票无需找零钱。</span></p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162822_04400.jpg" alt="" style="border: 0px;"></p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>车站设有洗手间。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为了满足乘客乘坐地铁期间的如厕需求，车站在站台设有洗手间。</span></p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162902_25240.jpg" alt="" width="800" height="604" title="" align="" style="border: 0px;"></p>',
            '<p style="margin: 0px; padding: 0px; text-align: center;"><img src="https://www.gzhd.net/UploadFile/image/20180530/20180530162902_46230.jpg" alt="" style="border: 0px;"></p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>增设自动补票机。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为方便乘客处理票务事务，乘客可通过自助补票机自行补票，大大节约了人工补票的等候时间。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>设宽通道闸机。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为了提高携带大件行李、推婴儿车等乘客的进站效率，车站在两端分别设置了1台宽通道闸机。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>增加母婴室。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">为了给哺乳乘客提供私密的舒适的空间，车站在站厅设有独立的母婴室，配置座椅、婴儿护理台等。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;">&nbsp;</p>',
            '<section data-id="92790" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_117" data-width="100%"><section class="bizsvr_118"><section class="bizsvr_119">',
            '<p style="margin: 0px; padding: 0px;"><strong>引入多元共享服务。</strong></p>',
            '</section></section><section class="bizsvr_121" data-width="100%"><section class="bizsvr_122"></section></section></section></section>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_100">在原有人工租借便民雨伞服务的基础上，引入共享雨伞，实现了借还全智能化，更好地满足雨天乘客出行的借伞需求。</span></p>',
            '</section></section></section></section></section></section>',
            '<p class="bizsvr_0" style="margin: 0px; padding: 0px; color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; text-align: center;">&nbsp;</p>',
            '<section data-id="92407" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_18" data-width="100%"><section class="bizsvr_19"><section class="bizsvr_20" data-width="100%"><section class="bizsvr_21"><br>',
            '</section></section><section class="bizsvr_24"><section class="bizsvr_25" data-width="100%">',
            '<p class="bizsvr_26" data-width="100%" style="margin: 0px; padding: 0px;"><span class="bizsvr_27"><strong>开通半年客流逐步增加</strong></span></p>',
            '</section></section><section class="bizsvr_28" data-width="100%"><section class="bizsvr_29" data-width="100%"><br>',
            '</section></section></section></section></section></section><section data-id="92238" data-tools="135编辑器" style="color: rgb(102, 102, 102); font-family: &quot;Microsoft Yahei&quot;, arial, 宋体; border-width: 0px; box-sizing: border-box;"><section data-id="91857" data-tools="135编辑器" style="border-width: 0px; box-sizing: border-box;"><section data-role="paragraph" style="border-width: 0px; box-sizing: border-box;"><section class="bizsvr_30" data-width="100%"><section class="bizsvr_31"><section class="bizsvr_32" data-width="98%"><section class="bizsvr_33">',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_188">九号线自去年12月<span class="bizsvr_189">28</span>日开通以来已有半年，运营情况怎么样？清塘站开通后，九号线的客流又将有哪些变化？30日上午，广州地铁在宣布清塘站开通消息的同时，也公布了九号线半年来的有关运营数据。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_188">据广州地铁介绍，截至5月<span class="bizsvr_189">20</span>日，九号线行车间隔约6分半钟<span class="bizsvr_189">，</span>最大满载率<span class="bizsvr_189">46%</span>，列车准点率达到99.99%，日开行列车293列次，累计开行列车4.2万列次。日均客流量近<span class="bizsvr_189">10</span>万人次，三号线与九号线的日均换乘客流量达<span class="bizsvr_189">3.6</span>万人次，最高日客流量在今年1月<span class="bizsvr_189">1</span>日，超过了19万人次。全线工作日的客流高峰期集中在上午<span class="bizsvr_189">7</span>点至<span class="bizsvr_189">8</span>点，而全线客流量前三个车站分别是：高增站3.7万人次、花都广场站<span class="bizsvr_189">1.4</span>万人次、花城路站<span class="bizsvr_189">1.2</span>万人次。</span></p>',
            '<p class="bizsvr_34" style="margin: 0px; padding: 0px;"><span class="bizsvr_188">广州地铁表示，随着市民对九号线的日渐熟悉，九号线的客流稳步上升，日均客流量从1月份的<span class="bizsvr_189">9</span>万余人次，逐步增加至5月份的<span class="bizsvr_189">10</span>万余人次。考虑新线客流培育的影响预计到下半年日均客运量有望突破<span class="bizsvr_189">11</span>万。</span></p>',
            '</section></section></section></section></section></section></section></div>'].join(""),
        add_time: "2018-5-31",
        category: 2,
        links: "https://www.zhanglitong.com/mobile/index.php?moduleid=21&itemid=1659"
    },
    {
        id: 6,
        title: "掌里通智慧城市布局手机点餐系统",
        img: "https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png?imageView&thumbnail=750x0&quality=85&type=jpg&interlace=1",
        summary: "随着智能手机的不断普及，2G、3G、4G、5G甚至将来的更高级别的手机互联网络的不断推陈出新，通过手机实现上网将变的越来越流畅，这将带来手机上网比例不断攀升。现在出门可以不带钱、不带银行卡，但是不能不带手机。满大街的“低头族”告诉我们，手机已成为人类生活和工作中的至关重要的工具。并且人类对更方便快捷的工作和生活方式的追求是无止尽的。“民以食为天",
        content: ["<div class=\"content\">",
            "        <div class=\"page js-page on\">",
            "            <p>随着智能手机的不断普及，2G、3G、4G、5G甚至将来的更高级别的手机互联网络的不断推陈出新，通过手机实现上网将变的越来越流畅，这将带来手机上网比例不断攀升。现在出门可以不带钱、不带银行卡，但是不能不带手机。满大街的“低头族”告诉我们，手机已成为人类生活和工作中的至关重要的工具。并且人类对更方便快捷的工作和生活方式的追求是无止尽的。“民以食为天”，传统餐饮业于互联网的融合更是大势所趋，“掌里通智慧餐饮管理系统”紧密贴合市场所需，解民生之所需，未来的市场将不可限量。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/5/5f/5f3fe311b4fad46519f7d7f6fe93a8cc.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>近日，掌里通智慧城市给广州带来了最新的手机点餐解决方案，结合“吃在广州” 的特质，给出了手机智慧点餐的方案，将在未来让广州这个“美食之都”的餐饮业大大提质增效。</p><p>掌里通智慧城市创始人凌腾云表示，从自助化程度高低进行划分，餐饮业的点餐方式已经从 1.0 的收银台点餐、2.0 的机器点餐，逐步进入 3.0 的手机点餐时代。无论是从互动、体验、成本、还是消费频次上，手机点餐已经成为商家门店跟消费者之间的全新沟通方式。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/1/19/192aa42e7991d345206279380eea0fca.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>而在手机点餐目前主要的APP点餐、H5点餐、掌里通点餐三种方式。从开发维护成本、用户获取门槛、流程体验效果、用户留存、消息触达能力进行分析。掌里通的模式都更轻更好，更有潜力成为未来手机点餐的主流模式。</p><p>凌腾云表示，用掌里通点餐解决方案帮助商家在点餐环节上提升餐厅运营效率，讲引导顾客消费，带来客单量的进一步提升。</p><div class=\"photo\">",
            "            <a href=\"https://cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png\">",
            "                <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/4/41/419078bba8a1e7f87364ad3248e44d60.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "                <span></span>",
            "            </a>",
            "        </div><p>凌腾云介绍，作为“美食之都”，在餐饮业发展方面有着天然优势，掌里通智慧城市立足在广州也是看中了广州身上这种优良的餐饮文化基因，接下来，广州将是手机点餐布局的重要战场。同时，通过这种优化，也将大大实现广州餐饮业服务的新升级。掌里通智慧城市已经覆盖了微餐、快餐、饮品、点餐平台排队预约服务等。</p></div><div class=\"page js-page\"><div class=\"photo\">",
            "        <a href=\"https://cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png\">",
            "            <img alt=\"\" data-src=\"//cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png\" src=\"https://cms-bucket.nosdn.127.net/catchpic/1/1b/1be20164a51d2e97286efc26ea519cb9.png?imageView&amp;thumbnail=750x0&amp;quality=85&amp;type=jpg&amp;interlace=1\">",
            "            <span></span>",
            "        </a>",
            "    </div><p>凌腾云介绍，“智慧餐饮管理系统”全新面世，预订系统能够让用户随时随地向商家下单，节省了在餐厅排队等待的时间，预定成功后系统随即自动生成邀请函(邀请函包括餐厅名字，就餐时间，联系电话、地址)并发送到顾客的手机，顾客可以将此邀请函发给其他好友，同时页面会自动生成导航带你直接准确到达餐厅。预定成功后，用户还可以用掌里通智能餐饮预定系统在餐厅提前点餐，将菜单发送给同行好友，大大缩短用户的等待时间，餐厅就可以提前准备点单的菜式。当用户到达餐厅时即可享用，用户也可到店使用智能系统扫码点菜点菜、加菜等各种功能。商家还可通过掌里通与自身门店管理、订单管理、收银系统、运营流程等环节打通，进一步提升运营效率，为门店带来更多客源，提升盈利。全程智能化、自助化，大大提高服务效率。</p><p>此外，掌里通智慧城市各项功能展示清晰、商家进驻便利。进驻后可根据简单易操作的后台提示自行搭建，商家的优惠活动、特价商品可以即时、随心上传。更有二维码即时打印机，即刻生成专属于您的店铺收款二维码。</p><p>智慧城市是一个面向所有人类、为全人类服务大工程。“智慧城市”目标是使人类能更加便捷、高效地享受城市公共服务、更低成本、更精准地寻找市场并获取经济效益。在政府公共信息传播、政务办公、生活预定、出行计划、生活娱乐、商业推广等方面，“智慧城市”的作用将体现的淋漓尽致，广州掌里通网络科技有限公司打造的手机平台——“掌里通智慧城市”是一个综合性的利商便民平台，“掌里通智慧城市”平台的最终目标是实现“掌里通天下”，让所有人都能享受到“智慧城市”给生活和工作带来的便利。</p><p>(原标题：掌里通智慧城市布局手机点餐系统)</p>",
            "        <div class=\"otitle_editor\">",
            "            <p class=\"otitle\">",
            "                (原标题：掌里通智慧城市布局手机点餐系统)",
            "            </p>",
            "        </div>",
            "    </div>",
            "    </div>"].join(""),
        add_time: "2018-06-12",
        category: 3,
        links: "https://3g.163.com/news/article/D4DHJQS400018AOP.html#adaptation=pc"
    },

];

var newsTypes = [
    {
        id: 0,
        name: "重点关注"
    },
    {
        id: 1,
        name: "公司要闻"
    },
    {
        id: 2,
        name: "热点专题"
    },
    {
        id: 3,
        name: "最新动态"
    }
];
